# -*- coding: utf-8 -*-
"""Copia de Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkICrd154A5vuElxOPYZwf6wKXKJ_y8x
"""

import streamlit as st
st.title("Mi primera Aplicacion")
st.header("este es un encabezado")
st.subheader("este es un subencabezado")
st.write("Hola Mundo")